name: Deploy

permissions:
  contents: write

on:
  push:
    branches: [self-depoly]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - run: pnpm recursive run build

      - run: npx next export
        working-directory: ./packages/demo

      - run: touch packages/demo/out/.nojekyll

      - uses: actions/upload-artifact@v3
        with:
          name: pages
          path: packages/demo/out

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: packages/demo/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
